### PR TITLE
Add NDE Art & Architecture Thesaurus

### PR DESCRIPTION
**Pull request by raboof**
The AAT was already included, but the NDE exposes the Dutch localization
of this thesaurus.

### CODE REVIEW

**Comment by raboof** [comment]
Tested at https://bibliotheek.eicas.nl

**Comment by Xentropics** [comment]
Closing this as I updated all sources in the upcoming update...

**Comment by raboof** [comment]
> Closing this as I updated all sources in the upcoming update...

I'm not sure I understand - is this an update not shared here yet? I don't see it on the ndeterms-update-1 branch either.

Anyway, looking forward to it ;)

**Comment by Xentropics** [comment]
F5 🤓

**Comment by Xentropics** [comment]
Please read my comment here: https://github.com/omeka-s-modules/ValueSuggest/pull/62 There's a breaking change in that PR. Can probably be mitigated by some mutations in the database (changing the datatype id's). Sjors Valk suggested to publish it anyway. If you (@raboof) would like to discuss, please let me know.

**Comment by raboof** [comment]
> Please read my comment here: [omeka-s-modules#62](https://github.com/omeka-s-modules/ValueSuggest/pull/62) There's a breaking change in that PR. Can probably be mitigated by some mutations in the database (changing the datatype id's). Sjors Valk suggested to publish it anyway. If you (@raboof) would like to discuss, please let me know.

Thanks for the heads-up, I commented on the PR!

**Pull request closed without merging**
